BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS albums (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  edition_year INTEGER NOT NULL,
  total_stickers INTEGER NOT NULL CHECK (total_stickers > 0),
  description TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS album_features (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id INTEGER NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  feature_key TEXT NOT NULL,
  feature_value TEXT NOT NULL,
  UNIQUE (album_id, feature_key)
);

CREATE TABLE IF NOT EXISTS sticker_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE,
  name TEXT NOT NULL UNIQUE,
  group_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sticker_types (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS variant_types (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('base', 'parallel', 'extra')),
  odds_text TEXT,
  is_default BOOLEAN NOT NULL DEFAULT false,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS stickers (
  code TEXT PRIMARY KEY,
  canonical_code TEXT NOT NULL UNIQUE,
  album_id INTEGER NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  album_order INTEGER NOT NULL,
  source_sheet TEXT NOT NULL,
  source_row INTEGER NOT NULL,
  context_name TEXT NOT NULL,
  section_id BIGINT REFERENCES sticker_sections(id),
  team_id BIGINT REFERENCES teams(id),
  sticker_type_code TEXT NOT NULL REFERENCES sticker_types(code),
  subject TEXT NOT NULL,
  sticker_number INTEGER,
  initial_quantity INTEGER NOT NULL DEFAULT 0 CHECK (initial_quantity >= 0),
  initial_owned BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (section_id IS NOT NULL OR team_id IS NOT NULL),
  UNIQUE (album_id, album_order)
);

CREATE INDEX IF NOT EXISTS idx_stickers_album_order ON stickers(album_id, album_order);
CREATE INDEX IF NOT EXISTS idx_stickers_team_id ON stickers(team_id);
CREATE INDEX IF NOT EXISTS idx_stickers_section_id ON stickers(section_id);
CREATE INDEX IF NOT EXISTS idx_stickers_context_name ON stickers(context_name);
CREATE INDEX IF NOT EXISTS idx_stickers_subject ON stickers(subject);

CREATE TABLE IF NOT EXISTS collector_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  telegram_chat_id TEXT UNIQUE,
  telegram_username TEXT UNIQUE,
  first_name TEXT,
  last_name TEXT,
  display_name TEXT,
  language_code TEXT CHECK (language_code IN ('en', 'es', 'zh')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE IF EXISTS collector_profiles ADD COLUMN IF NOT EXISTS telegram_username TEXT UNIQUE;
ALTER TABLE IF EXISTS collector_profiles ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE IF EXISTS collector_profiles ADD COLUMN IF NOT EXISTS last_name TEXT;
ALTER TABLE IF EXISTS collector_profiles ADD COLUMN IF NOT EXISTS language_code TEXT CHECK (language_code IN ('en', 'es', 'zh'));

CREATE TABLE IF NOT EXISTS user_albums (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  album_id INTEGER NOT NULL REFERENCES albums(id) ON DELETE RESTRICT,
  owner_id UUID NOT NULL REFERENCES collector_profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CHECK (btrim(name) <> '')
);

CREATE INDEX IF NOT EXISTS idx_user_albums_owner ON user_albums(owner_id);
CREATE INDEX IF NOT EXISTS idx_user_albums_album ON user_albums(album_id);
CREATE INDEX IF NOT EXISTS idx_user_albums_active ON user_albums(owner_id, deleted_at);

CREATE TABLE IF NOT EXISTS user_album_members (
  user_album_id UUID NOT NULL REFERENCES user_albums(id) ON DELETE CASCADE,
  collector_id UUID NOT NULL REFERENCES collector_profiles(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('owner', 'member')),
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  left_at TIMESTAMPTZ,
  PRIMARY KEY (user_album_id, collector_id)
);

CREATE INDEX IF NOT EXISTS idx_user_album_members_collector
  ON user_album_members(collector_id, left_at);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_album_owner_member
  ON user_album_members(user_album_id)
  WHERE role = 'owner' AND left_at IS NULL;

CREATE TABLE IF NOT EXISTS collector_active_albums (
  collector_id UUID PRIMARY KEY REFERENCES collector_profiles(id) ON DELETE CASCADE,
  user_album_id UUID NOT NULL REFERENCES user_albums(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_collector_active_albums_album
  ON collector_active_albums(user_album_id);

CREATE TABLE IF NOT EXISTS user_album_items (
  user_album_id UUID NOT NULL REFERENCES user_albums(id) ON DELETE CASCADE,
  sticker_code TEXT NOT NULL REFERENCES stickers(code) ON DELETE CASCADE,
  variant_code TEXT NOT NULL REFERENCES variant_types(code) DEFAULT 'BASE',
  quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_album_id, sticker_code, variant_code)
);

CREATE INDEX IF NOT EXISTS idx_user_album_items_sticker ON user_album_items(sticker_code);
CREATE INDEX IF NOT EXISTS idx_user_album_items_variant ON user_album_items(variant_code);

CREATE TABLE IF NOT EXISTS user_album_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_album_id UUID NOT NULL REFERENCES user_albums(id) ON DELETE CASCADE,
  collector_id UUID REFERENCES collector_profiles(id) ON DELETE SET NULL,
  sticker_code TEXT NOT NULL REFERENCES stickers(code) ON DELETE CASCADE,
  variant_code TEXT NOT NULL REFERENCES variant_types(code) DEFAULT 'BASE',
  action TEXT NOT NULL CHECK (action IN ('add', 'remove', 'set', 'undo')),
  previous_quantity INTEGER NOT NULL CHECK (previous_quantity >= 0),
  current_quantity INTEGER NOT NULL CHECK (current_quantity >= 0),
  quantity_delta INTEGER NOT NULL,
  message_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_album_events_album_created
  ON user_album_events(user_album_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_album_events_collector_created
  ON user_album_events(collector_id, created_at DESC);

CREATE TABLE IF NOT EXISTS album_share_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_album_id UUID NOT NULL REFERENCES user_albums(id) ON DELETE CASCADE,
  from_collector_id UUID NOT NULL REFERENCES collector_profiles(id) ON DELETE CASCADE,
  to_collector_id UUID NOT NULL REFERENCES collector_profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  answered_at TIMESTAMPTZ,
  CHECK (from_collector_id <> to_collector_id)
);

CREATE INDEX IF NOT EXISTS idx_album_share_requests_to_status
  ON album_share_requests(to_collector_id, status, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_album_share_requests_pending
  ON album_share_requests(user_album_id, to_collector_id)
  WHERE status = 'pending';

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION ensure_user_album_owner_member()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO user_album_members (user_album_id, collector_id, role, left_at)
  VALUES (NEW.id, NEW.owner_id, 'owner', NULL)
  ON CONFLICT (user_album_id, collector_id) DO UPDATE SET
    role = 'owner',
    left_at = NULL;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_albums_updated_at ON albums;
CREATE TRIGGER set_albums_updated_at
BEFORE UPDATE ON albums
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_collector_profiles_updated_at ON collector_profiles;
CREATE TRIGGER set_collector_profiles_updated_at
BEFORE UPDATE ON collector_profiles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_user_albums_updated_at ON user_albums;
CREATE TRIGGER set_user_albums_updated_at
BEFORE UPDATE ON user_albums
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS ensure_user_album_owner_member_after_insert ON user_albums;
CREATE TRIGGER ensure_user_album_owner_member_after_insert
AFTER INSERT ON user_albums
FOR EACH ROW
EXECUTE FUNCTION ensure_user_album_owner_member();

DROP TRIGGER IF EXISTS set_collector_active_albums_updated_at ON collector_active_albums;
CREATE TRIGGER set_collector_active_albums_updated_at
BEFORE UPDATE ON collector_active_albums
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_user_album_items_updated_at ON user_album_items;
CREATE TRIGGER set_user_album_items_updated_at
BEFORE UPDATE ON user_album_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO albums (slug, name, edition_year, total_stickers, description)
VALUES (
  'panini-fifa-world-cup-2026',
  'Panini FIFA World Cup 2026',
  2026,
  994,
  'Album tracker imported from AlbumData.xlsx.'
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  edition_year = EXCLUDED.edition_year,
  total_stickers = EXCLUDED.total_stickers,
  description = EXCLUDED.description;

INSERT INTO album_features (album_id, feature_key, feature_value)
SELECT albums.id, feature_key, feature_value
FROM albums
CROSS JOIN (
  VALUES
    ('total_stickers', 'The collection has over 980 stickers; AlbumData.xlsx currently defines 994 catalog rows.'),
    ('team_coverage', 'Covers 48 participating nations with dedicated pages, player slots, badges, and team info.'),
    ('special_inserts', 'Supports Golden Ballers, Momentum cards, and online-exclusive Crumple parallels.'),
    ('coca_cola', 'Includes Coca-Cola bonus stickers with dedicated album spaces.'),
    ('digital_version', 'A digital collection is available via the FIFA Panini Collection app.'),
    ('base_stickers', 'Base stickers cover teams, stadiums, special sections, and key players.'),
    ('parallels', 'Parallel variants include Blue 1:2, Red 1:25, Purple 1:200, Green 1:1,400, and Black 1-of-1.'),
    ('extra_stickers', 'Rare Extra Sticker editions appear at 1:100 packs and support Bronze, Silver, and Gold variants.')
) AS features(feature_key, feature_value)
WHERE albums.slug = 'panini-fifa-world-cup-2026'
ON CONFLICT (album_id, feature_key) DO UPDATE SET
  feature_value = EXCLUDED.feature_value;

INSERT INTO sticker_types (code, name, description)
VALUES
  ('BADGE', 'Badge', 'Team badge or crest slot.'),
  ('NORMAL', 'Normal', 'Regular player sticker.'),
  ('SPECIAL', 'Special', 'Special insert, intro, Coca-Cola, champion, or themed sticker.'),
  ('TEAM', 'Team', 'Team info or team page sticker.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description;

INSERT INTO variant_types (code, name, category, odds_text, is_default, sort_order)
VALUES
  ('BASE', 'Base', 'base', NULL, true, 10),
  ('PARALLEL_BLUE', 'Blue Crumple Parallel', 'parallel', '1:2 packs', false, 20),
  ('PARALLEL_RED', 'Red Crumple Parallel', 'parallel', '1:25 packs', false, 30),
  ('PARALLEL_PURPLE', 'Purple Crumple Parallel', 'parallel', '1:200 packs', false, 40),
  ('PARALLEL_GREEN', 'Green Crumple Parallel', 'parallel', '1:1,400 packs', false, 50),
  ('PARALLEL_BLACK', 'Black Crumple Parallel', 'parallel', '1-of-1', false, 60),
  ('EXTRA_BRONZE', 'Extra Sticker Bronze', 'extra', 'Extra Sticker editions appear at 1:100 packs', false, 70),
  ('EXTRA_SILVER', 'Extra Sticker Silver', 'extra', 'Extra Sticker editions appear at 1:100 packs', false, 80),
  ('EXTRA_GOLD', 'Extra Sticker Gold', 'extra', 'Extra Sticker editions appear at 1:100 packs', false, 90)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  odds_text = EXCLUDED.odds_text,
  is_default = EXCLUDED.is_default,
  sort_order = EXCLUDED.sort_order;

CREATE OR REPLACE VIEW v_album_catalog_summary AS
SELECT
  albums.slug AS album_slug,
  albums.name AS album_name,
  count(stickers.code) AS total_stickers,
  count(stickers.code) FILTER (WHERE stickers.team_id IS NOT NULL) AS team_related_stickers,
  count(stickers.code) FILTER (WHERE stickers.section_id IS NOT NULL) AS section_stickers,
  count(DISTINCT stickers.team_id) FILTER (WHERE stickers.team_id IS NOT NULL) AS total_teams,
  count(stickers.code) FILTER (WHERE stickers.sticker_type_code = 'SPECIAL') AS special_stickers,
  count(stickers.code) FILTER (WHERE stickers.context_name = 'SECTION 3') AS coca_cola_stickers
FROM albums
LEFT JOIN stickers ON stickers.album_id = albums.id
GROUP BY albums.id;

CREATE OR REPLACE VIEW v_user_albums AS
SELECT
  collector_profiles.id AS collector_id,
  collector_profiles.telegram_chat_id,
  collector_profiles.telegram_username,
  user_albums.id AS user_album_id,
  user_albums.name AS user_album_name,
  albums.slug AS album_slug,
  albums.name AS album_template_name,
  user_albums.owner_id,
  owner_profiles.telegram_username AS owner_telegram_username,
  owner_profiles.display_name AS owner_display_name,
  user_album_members.role,
  user_albums.owner_id <> collector_profiles.id AS is_shared,
  collector_active_albums.user_album_id IS NOT NULL AS is_active,
  user_album_members.joined_at,
  user_albums.created_at,
  user_albums.updated_at
FROM collector_profiles
JOIN user_album_members
  ON user_album_members.collector_id = collector_profiles.id
  AND user_album_members.left_at IS NULL
JOIN user_albums
  ON user_albums.id = user_album_members.user_album_id
  AND user_albums.deleted_at IS NULL
JOIN albums ON albums.id = user_albums.album_id
JOIN collector_profiles AS owner_profiles ON owner_profiles.id = user_albums.owner_id
LEFT JOIN collector_active_albums
  ON collector_active_albums.collector_id = collector_profiles.id
  AND collector_active_albums.user_album_id = user_albums.id;

CREATE OR REPLACE VIEW v_collection_progress AS
SELECT
  collector_profiles.id AS collector_id,
  collector_profiles.telegram_chat_id,
  collector_profiles.telegram_username,
  user_albums.id AS user_album_id,
  user_albums.name AS user_album_name,
  albums.slug AS album_slug,
  albums.name AS album_template_name,
  user_albums.owner_id,
  owner_profiles.telegram_username AS owner_telegram_username,
  owner_profiles.display_name AS owner_display_name,
  user_albums.owner_id <> collector_profiles.id AS is_shared,
  collector_active_albums.user_album_id IS NOT NULL AS is_active,
  count(stickers.code) AS total_stickers,
  count(user_album_items.sticker_code) FILTER (
    WHERE user_album_items.variant_code = 'BASE'
      AND user_album_items.quantity > 0
  ) AS owned_stickers,
  count(stickers.code) - count(user_album_items.sticker_code) FILTER (
    WHERE user_album_items.variant_code = 'BASE'
      AND user_album_items.quantity > 0
  ) AS missing_stickers,
  coalesce(sum(GREATEST(user_album_items.quantity - 1, 0)) FILTER (
    WHERE user_album_items.variant_code = 'BASE'
  ), 0) AS duplicate_stickers,
  round(
    (
      count(user_album_items.sticker_code) FILTER (
        WHERE user_album_items.variant_code = 'BASE'
          AND user_album_items.quantity > 0
      )::numeric
      / nullif(count(stickers.code), 0)
    ) * 100,
    2
  ) AS completion_percentage
FROM collector_profiles
JOIN user_album_members
  ON user_album_members.collector_id = collector_profiles.id
  AND user_album_members.left_at IS NULL
JOIN user_albums
  ON user_albums.id = user_album_members.user_album_id
  AND user_albums.deleted_at IS NULL
JOIN albums ON albums.id = user_albums.album_id
JOIN collector_profiles AS owner_profiles ON owner_profiles.id = user_albums.owner_id
JOIN stickers ON stickers.album_id = albums.id
LEFT JOIN user_album_items
  ON user_album_items.user_album_id = user_albums.id
  AND user_album_items.sticker_code = stickers.code
  AND user_album_items.variant_code = 'BASE'
LEFT JOIN collector_active_albums
  ON collector_active_albums.collector_id = collector_profiles.id
  AND collector_active_albums.user_album_id = user_albums.id
GROUP BY collector_profiles.id, user_albums.id, albums.id, owner_profiles.id, collector_active_albums.user_album_id;

CREATE OR REPLACE VIEW v_missing_stickers AS
SELECT
  collector_profiles.id AS collector_id,
  collector_profiles.telegram_chat_id,
  collector_profiles.telegram_username,
  user_albums.id AS user_album_id,
  user_albums.name AS user_album_name,
  albums.slug AS album_slug,
  user_albums.owner_id <> collector_profiles.id AS is_shared,
  stickers.code,
  stickers.canonical_code,
  stickers.context_name,
  stickers.subject,
  stickers.sticker_type_code
FROM collector_profiles
JOIN user_album_members
  ON user_album_members.collector_id = collector_profiles.id
  AND user_album_members.left_at IS NULL
JOIN user_albums
  ON user_albums.id = user_album_members.user_album_id
  AND user_albums.deleted_at IS NULL
JOIN albums ON albums.id = user_albums.album_id
JOIN stickers ON stickers.album_id = albums.id
LEFT JOIN user_album_items
  ON user_album_items.user_album_id = user_albums.id
  AND user_album_items.sticker_code = stickers.code
  AND user_album_items.variant_code = 'BASE'
WHERE coalesce(user_album_items.quantity, 0) = 0;

CREATE OR REPLACE VIEW v_duplicate_stickers AS
SELECT
  collector_profiles.id AS collector_id,
  collector_profiles.telegram_chat_id,
  collector_profiles.telegram_username,
  user_albums.id AS user_album_id,
  user_albums.name AS user_album_name,
  albums.slug AS album_slug,
  user_albums.owner_id <> collector_profiles.id AS is_shared,
  user_album_items.sticker_code AS code,
  stickers.canonical_code,
  user_album_items.variant_code,
  stickers.context_name,
  stickers.subject,
  user_album_items.quantity,
  user_album_items.quantity - 1 AS duplicate_quantity
FROM collector_profiles
JOIN user_album_members
  ON user_album_members.collector_id = collector_profiles.id
  AND user_album_members.left_at IS NULL
JOIN user_albums
  ON user_albums.id = user_album_members.user_album_id
  AND user_albums.deleted_at IS NULL
JOIN albums ON albums.id = user_albums.album_id
JOIN user_album_items ON user_album_items.user_album_id = user_albums.id
JOIN stickers ON stickers.code = user_album_items.sticker_code
WHERE user_album_items.quantity > 1;

COMMIT;
